Feature/issue 29/account login
SOEN490-SportsApp/SportsApp pull request #118
Opened 2024-11-07 02:49 UTC by yousfino

Related Feature: #29 

- Implement login page UI
- Add tests for login page
- TODO: integration with backend

Login page UI:

![image](https://github.com/user-attachments/assets/4434ec75-ab26-4cad-ad4f-a15fcdeebd28)

2024-11-07 03:40 UTC, KhalilGarali commented
Before merging this we might want to complete these first:
- use the logo file and not a screenshot for better quality
- adjust tailwind classes to better render the UI dynamically between different sizes of screens (Might need to meet with me Youssef so that register and login pages are coherent)

2024-11-08 23:46 UTC, walidoow reviewed
⚠️ Please use squash and merge here when you merge this PR @yousfino @NicolasChelico @KhalilGarali @JRB958 @MonikaaMoanes

2024-11-09 03:20 UTC, KhalilGarali requested changes

2024-11-09 03:26 UTC, yousfino commented on ClientApp/app/auth/login.tsx
> +              pattern: { value: /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/, message: "Invalid email" }
good catch! just fixed!

2024-11-09 03:28 UTC, yousfino commented on ClientApp/__tests__/auth/login.test.tsx
> +        });
agreed! done!

2024-11-09 03:49 UTC, yousfino commented
This PR has been moved to another branch and has been resolved there due to a conflict with the current remote branch. Therefore, this PR had been closed without a merge.

Please click [here](https://github.com/SOEN490-SportsApp/SportsApp/pull/128) to view the revised version of this PR.

2024-11-09 03:49 UTC, closed without merging