GH-108: [feat] Added profile preference section after creating account
SOEN490-SportsApp/SportsApp pull request #119
Opened 2024-11-07 02:56 UTC by NicolasChelico

The following PR includes the addition of the Profile preference page which is the page a user is redirected to after successful account creation to initialize their preferences. 

- Test cases refactor are incoming
- UI is subject to change in next sprint for spreading out over two pages making it a multi step process to remove clutter. ** To keep in mind**

<img width="120" alt="Screenshot 2024-11-09 at 3 25 05 PM" src="https://github.com/user-attachments/assets/8fed4184-fb43-44aa-b4ff-4e715a64c0de">

2024-11-07 04:04 UTC, KhalilGarali commented
I think we should wait for @NicolasChelico and @walidoow agree on the models before merging this PR.

2024-11-08 06:10 UTC, KhalilGarali commented
When I checkout to your branch to test this is what I saw:
<img width="238" alt="image" src="https://github.com/user-attachments/assets/6e096a20-167a-4ae6-b15f-e9f3592a90d4">

I'm not sure if this is UI friendly /  good user experience. You can maybe change it like so: take off the blue button, make the logo clikable to choose the date and display the data as string in the field. So the field would be readonly.

Also there is a small bug when I tested: when you choose your date for the first time, you cannot change it back again. This keeps popping up:
<img width="221" alt="image" src="https://github.com/user-attachments/assets/884d1398-a314-4c81-ad49-b14214efca5a">

Steps to repo:
- open date time picker
- choose for example November 7th 2024. click done.
- open date picker time again.

2024-11-09 03:19 UTC, KhalilGarali requested changes

2024-11-09 03:19 UTC, KhalilGarali commented on ClientApp/app/auth/profilePreferenceForm.tsx
> +        {errors.firstName && (
@JRB958

2024-11-09 03:32 UTC, NicolasChelico commented on ClientApp/app/auth/profilePreferenceForm.tsx
> +        {errors.firstName && (
I agrée with you but this is using prettier formatting. I can move to other way instead

2024-11-10 00:49 UTC, KhalilGarali approved these changes
Approved

2024-11-10 00:50 UTC, JRB958 approved these changes
changes look good

2024-11-10 00:50 UTC, merged