Feature/issue 103/refactor add skill level field
SOEN490-SportsApp/SportsApp pull request #182
Opened 2024-11-27 05:47 UTC by DanDuguay

This PR is to complete issue #103.

## Changes

- Added a skillLevelEnum with values "BEGINNER", "INTERMEDIATE", and "ADVANCED" to be used when creating/joining events.
- Added Unit tests

2024-12-16 03:11 UTC, Ziadsharkos submitted a review, later dismissed
Good additions, great work!

2024-12-17 00:14 UTC, walidoow requested changes

2024-12-17 00:14 UTC, walidoow commented on Microservices/event-service/src/main/java/app/sportahub/eventservice/dto/response/EventResponse.java
>  public record EventResponse(String id, String eventName, String eventType, String sportType, Location location,
Can you replace the Location object in response with LocationResponse (you will need to create it).

2024-12-17 19:28 UTC, walidoow commented
@DanDuguay you could have named it location directly instead of locationRequest.
![image](https://github.com/user-attachments/assets/9553bf58-95f0-4d5f-baec-0d93dd9e6032)

That way you would not have to specifically map the fields in the mapper.
![image](https://github.com/user-attachments/assets/83be3959-9d55-495a-b9b7-5688bf5ed2fe)

2024-12-17 19:33 UTC, walidoow approved these changes
Looks good, great job 👍

2024-12-17 20:23 UTC, Ziadsharkos approved these changes

2024-12-18 00:19 UTC, walidoow commented
@DanDuguay watch out you have duplicated commits

2024-12-18 00:26 UTC, walidoow approved these changes

2024-12-18 00:26 UTC, Ziadsharkos approved these changes

2024-12-18 00:27 UTC, merged