GH-81: [feat] delete event
SOEN490-SportsApp/SportsApp pull request #188
Opened 2024-12-20 00:06 UTC by wolfie7679

- Created the delete event endpoint
- Created unit tests associated with endpoint

2024-12-21 02:29 UTC, walidoow requested changes
Aside from the trailing spaces, everything looks good, I will accept the PR once you make that change. Good work!

2024-12-21 02:29 UTC, walidoow commented on Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
> +
Can you delete these trailing spaces?

2024-12-21 02:38 UTC, wolfie7679 commented on Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
> +
sure

2024-12-23 19:43 UTC, walidoow approved these changes
Looks good to me! Great first PR 🥳

2024-12-23 22:54 UTC, Ziadsharkos approved these changes
Looks good to me!

2024-12-28 17:34 UTC, merged