Feature/issue 165/user settings
SOEN490-SportsApp/SportsApp pull request #191
Opened 2024-12-25 18:57 UTC by yousfino

Created the following pages:
- Settings Page - accessed through user profile.
- Notifications Page - accessed through Settings Page.
- Help Page - accessed through Settings Page.
- Language Page - accessed through Settings Page.
- Logout through Settings Page.

2024-12-29 22:02 UTC, KhalilGarali requested changes
Other than the comments I made, everything looks good!

2024-12-30 01:05 UTC, yousfino commented on ClientApp/app/(tabs)/profile/index.tsx
>                      <Text className="text-blue-600 font-semibold">Edit</Text>
done! thank you

2024-12-30 01:05 UTC, yousfino commented on ClientApp/app/(tabs)/profile/_layout.tsx
> +  return <Stack screenOptions={{ headerShown: true }} />;
resolved!

2024-12-30 01:15 UTC, yousfino commented on ClientApp/app/(tabs)/profile/(settings)/settingsPage.tsx
> +      {/* Fixed Logout Button */}
what a great idea! done done!

2024-12-30 01:30 UTC, KhalilGarali approved these changes
Nice! Thank you!

2024-12-30 01:42 UTC, NicolasChelico approved these changes
good work

2024-12-30 01:42 UTC, merged